# ======================
# APP GENERAL
# ======================
spring.application.name=genesisClub
server.port=8080

# ======================
# JPA GENERAL
# ======================
spring.jpa.open-in-view=false

# ======================
# JWT
# ======================
jwt.private-key-path=jwtKeys/private_key.pem
jwt.public-key-path=jwtKeys/public_key.pem