spring.application.name=genesisClub
server.port=8080

spring.profiles.active=dev
# Configuración General
spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false

# JWT (Rutas relativas a la raíz del proyecto)
jwt.private-key-path=jwtKeys/private_key.pem
jwt.public-key-path=jwtKeys/public_key.pem
# FASE 3.3 - JWT Security: Expiración de token en 15 minutos (900000 ms)
jwt.expiration-time=900000

# Frontend URLs
app.front.url=http://localhost:4200


